name: ai_league_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^14.0.0

  flutter_svg: ^2.1.0

  image_picker: ^1.1.2

  record: ^6.0.0
  audioplayers: ^6.4.0

  panorama_viewer: ^2.0.4

  http: ^1.3.0
  http_parser: ^4.1.2
  
  path: ^1.9.1
  path_provider: ^2.1.5

  permission_handler: ^12.0.0+1
  flutter_sound: ^9.28.0
  speech_to_text: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/